[package]
name = "futures-threadpool"
version = "0.1.0"
authors = ["PvdBerg1998 <PvdBerg1998@users.noreply.github.com>"]
edition = "2018"

[dependencies]
crossbeam-channel = "0.3.8"
futures-preview = "0.3.0-alpha.13"
slotmap = { version = "0.3.0", features = ["unstable"] }
